### PR TITLE
Fixes mouse cursor texture issue

### PR DESCRIPTION
**Pull request by BraedonWooding**

### CODE REVIEW

**Comment by NogginBops** [comment]
What does this fix?
Is it the texture not being imported correctly?

I think all bug fix PRs should document the error they are fixing, either by linking to an issue or describing the bug.

**Comment by kd7uiy** [comment]
This was a discussion in the chat. Basically a warning message was showing up because it couldn't find the cursor. Adding the made it so the warning went away.

**Comment by NogginBops** [comment]
Yeah that is the import settings that are wrong, it's not the path that is wrong.
The import for the texture does not specify that it should be a cursor.
This should be fixed in the import settings rather than the way it's done here.

**Comment by BraedonWooding** [comment]
Are you sure?  I’ll have a look today.  But it went away when I specified it was a .png?

**Comment by BraedonWooding** [comment]
Ahhh yes you are right; I’ll submit a patch reverting the old patch and just fixing the import (I don’t know why specifying path removes the warning but it probably shouldn’t)

**Comment by NogginBops** [comment]
It probably removes the warning because it doesn't load the asset (which has the settings), and just loads the raw image instead or something. The cursor importer probably just does nothing with a png.

**Pull request merged**
