### PR TITLE
Fix PR#51 Bugs

### PR DESCRIPTION
**Pull request by Kjarrigan**
See #51 for the related discussion.

@koosemose To retrigger the cron-run (without waiting for a week) just delete the old job and create a new one.

PS: Should I rebase before merge or will you do it?

### CODE REVIEW

**Comment by koosemose** [comment]
Shouldn't be a need to rebase, it'll all get squashed in, and github will take care of the messy bits.

**Comment by koosemose** [comment]
Seems it wants a license, it's set on the repo, so I can only assume something has to be done to tell it what license the package is under?

```
Installing deploy dependencies
[Bintray Upload] Reading descriptor file: ./Scripts/bintray.json
[Bintray Upload] Creating package 'Prebuild-Binarys'...
[Bintray Upload] Bintray response: 400 Bad Request. Package for path 'orderoftheporcupine/ProjectPorcupine' was invalid. Package license is mandatory
[Bintray Upload] Creating version '2017.16'...
[Bintray Upload] Bintray response: 404 Not Found. Package 'Prebuild-Binarys' was not found
[Bintray Upload] Uploading file 'Build/Linux.zip' to Linux.zip
[Bintray Upload] Bintray response: 400 Bad Request. Failed to resolve package name
[Bintray Upload] Uploading file 'Build/MacOSX.zip' to MacOSX.zip
[Bintray Upload] Bintray response: 400 Bad Request. Failed to resolve package name
[Bintray Upload] Uploading file 'Build/Windows.zip' to Windows.zip
[Bintray Upload] Bintray response: 400 Bad Request. Failed to resolve package name
[Bintray Upload] Publishing version '2017.16' of package 'Prebuild-Binarys'...
[Bintray Upload] Bintray response: 404 Not Found. Package 'Prebuild-Binarys' was not found
```

**Comment by Kjarrigan** [comment]
I see. I created the Package on bintray by hand as well. Please do that too :smile:
The package should be called **Prebuild-Binarys**.

**Comment by koosemose** [comment]
And it works... is there anything preventing us from cding to a closer directory (for example `$(pwd)/Build/windows/` for the windows build)? As is the directory structure in the zip is excessively deep(`Users\travis\build\OrderOfThePorcupine\ProjectPorcupine\Build\windows\` for windows).

**Comment by Kjarrigan** [comment]
:+1: for the sucessfull build. 

And I think there is no reason to not cd deeper. I guess we could change

```
zip -q -r $(pwd)/Build/Linux.zip $(pwd)/Build/linux/
zip -q -r $(pwd)/Build/MacOSX.zip $(pwd)/Build/osx/
zip -q -r $(pwd)/Build/Windows.zip $(pwd)/Build/windows/
```

to 

```
cd $(pwd)/Build/
zip -q -r Linux.zip linux/
zip -q -r MacOSX.zip osx/
zip -q -r Windows.zip windows/
cd -
```

And a last suggestion - add a small section to the Readme containing a download link a few lines of explanation about this new setup. Like: "If you have no Unity but want to test the game we build weekly binary packages for Windows, MacOSX and Linux. You can find them here <LINK>. Don't expect these to work flawlessly. They are more like "snapshots" of the currente state and not supervised stable releases."

**Comment by koosemose** [comment]
Yeah, was just waiting until we had everything hammered out for certain to add to the Readme.

I'm not fond of even the linux/windows/osx being in the zip directory structure, but I suppose for weeklies it's okay. I'll see about making the cd tweaks to the script, reset the cron again and put up the download links.

**Pull request merged**
