### PR TITLE
[Fixes] Various Bug Fixes

### PR DESCRIPTION
**Pull request by BraedonWooding**
Love it, fixing for days.  This fixes a lot of xml issues (both in my code and others, though a lot more in my stuff since I did it wrong oops, and didn't realise for ages).  And some other little things here and there, fixes a ship line.  
- Fixes prototypes, 
- fixes files not being found and directories.  
- Along with fixes a weird conflict.  
- Just fixes a ton of stuff.

A good bug gif from pooling (laughed for quite a while):

tada

### CODE REVIEW

**Comment by BraedonWooding** [comment]
Tested quite extensively, works on save/load/new game and just generally throwing stuff around.  Fixes a few bugs that existed with creating a new game due to other things.

**Comment by koosemose** [comment]
Please try to make PR titles a little more descriptive or at least stick to more "professional" language, as the PR title is what shows up in the project commit log (Something as simple as "Various bug fixes" would do for a kitchen sink bug fix PR such as this)

**Comment by BraedonWooding** [comment]
Fair enough

**Comment by koosemose** [comment]
I'll trust your judgement on merging this... especially since you know I'm still neck deep in converter so it'll likely be you that has to fix anything you break ;D

**Pull request merged**
