### PR TITLE
[BIG] [WIP] Separation of World/Game

### LINKED ISSUE #91: Separation of 'World' and 'Game'
Partially this is for when/if multiple worlds ever come into existence but it is also just for cleaner code and to allow one to at minimum switch worlds without having to tear down every single system.  I propose that the worldcontroller (/world) should only contain references to classes which are world dependent, like for example temperature or atmosphere, where as the game controller should maintain the references for world independent classes like build mode controller or mouse controller.  Mainly opening this just to check on support since this was discussed before and I believe came to a consensus of the separation but its been a decently long time since :D.

### PR DESCRIPTION
**Pull request by BraedonWooding**
## Issues this fixes
#91

## Merge After
#81 #107 

## Current Status
Works completely in _World, but MainMenu is untested.

## Abstract
The secularism of Project Porcupine (lol).  This is going to be a big one, so I'm going to do it right.  I've documented changes across the board and this is being done so that 0 errors **will** persist.  This PR accomplishes just one goal, to separate the instances that exist in the 3 areas (WorldController, World, and GameController).

The decision was made in issue #91 to have a SystemController which will manage the creation of worlds and will hold all instances that are unique to a playthrough (or instance of the game).  The game controller will hold instances that are not unique to a playthrough but are unique to the 'game' (aka every time you reload the game by closing and reopening a new GameController is spawned).  World will hold everything unique to that world, such as temperature or the room manager.

Most controllers (that are multi-world based) now have two extra functions `AssignWorld(World world)` and `UnAssignWorld(World world)`, this is not for managing the current world but rather allows us to have multiple worlds.  So every single world is assigned, this means that we can run data on worlds that is the current world the user selects (for example let's say raiders destroy a bunch of furniture in one of your worlds that isn't your current the system will manage this without ANY issue, and with no special code from us).

## All Changes
- AudioManager
    - No longer a singleton
    - Static Class
    - Everything is created in static constructor
        - FMOD.System is now `static readonly`
- SoundController
    - Moved to GameController
- DriverInfo
    - Now exists in AudioManager, since it relates to that, it can be accessed like `AudioManger.DriverInfo`
    - Name is no longer a stringbuilder, it is now a string.
- CursorInfoDisplay
    - GetTileUnderDrag is gone (replaced by `World.GetRoundedTileAt`)
- BaseSpriteController, UtilitySpriteController, CharacterSpriteController, JobSpriteController, TileSpriteController, InventorySpriteController, ShipSpriteController, and FurnitureSpriteController
    - Now don't hold a reference to 'World' and are now all multi-world (you can assign multiple worlds to them).
    - Now exist in GameController
    - Now all have `AssignWorld(World world)` and `UnAssignWorld(World world)` to assign world delegates mostly.
    - It now uses proper neighbour finding, by using something like `*.Tile.North()` or `*.Tile.GetNeighbours()` (if it only needs one or two neighbours then the individual assignment is better or if it wants to do math on them, however if it is just passing them into another function the array is faster and doesn't lose any readability.
    - Get SuffixForNeighbour now requests a Tile rather than coordinates
- MainMenuController
    - Removed, its functionality exists in GameController
- WorldController
    - Being phased out, all its instances are either world dependent and go to World, system dependent and go to SystemController, or game dependent and go to GameController.
- MouseController
    - It loses its reference to BulidModeController and SpriteControllers (this was done in the Tooltip PR #81)
    - It now exists in SystemController
    - Soooo many more changes are done in Tooltip PR #81, so really the only change is where it exists and it loses a lot of its privates to become public properties and the old functions now just become public getters and private setters.
- DialogBoxManager
    - It now exists in GameController
    - Created at runtime
    - Now gets created ONLY in GameController (used to be created in MainMenuController too)
    - It has a CreateUI function to create the base UI needed for the main menu and CreateSystemUI to be done after SystemController has been created, which includes loading quest data, main menu items and dialogs for trade/jobs/quests.
- UIMenuController
    - Removed, all its functionality is spread into a mixture of SystemController and GameController
    - This means one less object is needed in the scene
- ModsManager
    - Now exists in GameController
    - No need to separate the loading of 'Menu' assets and 'Game' assets.
- CameraController
    - Now exists in SystemController
    - No longer holds a reference to camera data, since each world could have unique camera presets.
- BuildModeController
    - It now exists in GameController
- SettingsMenu
    - Now gets created ONLY in GameController (used to be created in MainMenuController too)
- PerformanceHUD
    - Now gets created ONLY in GameController (used to be created in MainMenuController too)
- CurrencyHUD
    - Now gets created ONLY in SystemController (used to be created in MainMenuController too)
- DevConsole
    - Now gets created ONLY in GameController (used to be created in MainMenuController too)
- TimeScale
    - Now gets created in SystemController
- ContextMenu
    - Now gets created in SystemController
- DateTimeDisplay
    - Now gets created in SystemController
- World
    - `World.Current` is gone (now a proper way is to access `GameController.Instance.CurrentSystem.CurrentWorld` or the shortcut `GameController.Instance.CurrentWorld`).
    - `GetRoundedTileAt(...)` takes in a vector and rounds each of the coords, this replaces the old function that exists in WorldController which was `GetTIleAtWorldCoord` really should exist in the world and the name was bad.  Made it more efficient too, the old way was to add `0.5f` then truncate which in reality was just a rounding operation, so now it just rounds to int, this also will massively reduce floating point errors.
   - Furthermore there is just an empty constructor with the ability to now `InitializeWithData(...)` or `InitializeFromJSON(...)`.  Just means that we can set CurrentWorld without breaking things or requiring some weird changes (later on as things get moved towards accepting multiple worlds it'll work better and we may even go back to the way things were).
- SpawnInventoryController
    - Now exists in SystemController
- QuestController
    - Now exists in SystemController
- AutosaveManager
    - Now exists in SystemController
- Path
    - Now exists in SystemController
    - We actually now maintain a reference to it
- Overlay
    - Created at runtime
- The Overlay Dropdown
    - Created at runtime (inside SystemController)
- OverlayMap
    - Created at runtime (inside SystemController)
    - Made variables either properties or constant fields
    - Made it more suitable for multiple worlds
    - We store a reference to it inside SystemController now (mainly just for when switching worlds happens)
- ContextMenu
    - Created at runtime (inside SystemController)
    - Fixed up the IEnumerable setup (all privates)
- Settings
    - No longer loads settings in static constructor, since game controller loads it properly
- SceneController
    - Removed, all the functionality now exists in game controller. 
- WorldGenerator
    - No longer relies on SceneController for data, it gets given it from constructor (bool generateAsteroids and string generateFile were the only missing ones).
- SystemController
    - `CurrentWorld` property now, linking to the current selected world (by the user).
    - Manages creation and deletion of worlds (as well as saving)
    - Should also allow for loading screens to exist :D.
    - LoadWorld loads from given save file
    - CreateWorld creates from given data
- GameController
    - MainScene and MainMenuScene variables added.  They are the name of the scenes.  This is just future proofing it.
    - ToMainScene, accepts either a filename or world data to create a world from.
    - ToMainMenu, goes back to the main menu and unassigns system and world data.
    - ActiveSceneChanged will control the actual building of the terrain and assigns the world as well as builds the UI.  Also it allows us to create a new world if the game is ran from `_World`
    - OpenedWorldScene is a new property that indicates if the user opened from the world scene, this is mainly for debug purposes (since it's quicker to run from _World and so a lot of people like to do it that way).
    - AssignWorld/UnAssignWorld just calls the properties that need to assign/unassign word data
    - CreateSystem creates a new system
    - QuitGame added, which is just the same as SceneController.QuitGame
    - Exists everywhere that MainMenuController would.
    - `GameController.Instance.CurrentSystem` now exists
    - `GameController.Instance.CurrentWorld` is a shortcut that just is the same as writing `GameController.Instance.CurrentSystem.CurrentWorld`.
    - circleCursorPrefab now exists in GameController
    - FileSaveBasePath, and GeneratorBasePath
        - Are no longer functions but getter properties, this is inline with the Microsoft standard for these kind of values (and Unity use it for stuff like Application.streamingAssetsPath)
        - They are now static
    - Doesn't get destroyed on load (the old one would be get destroyed on the creation of a new world)
- Fixed up a few inefficient IEnumerables (that are related to this stuff)
- Removed the Background gameobject from _World, it had a sprite renderer which was 'missing' its sprite and was always disabled and no reference to it existed in our code base.

So far that's all of the changes (*phew*)

### CODE REVIEW

**Comment by koosemose** [comment]
> SoundController
All of its functions are going to be moved to AudioManager since do we really need to different two sound managers...?

These are separate for a reason, do not merge them. 

AudioManager is the "low-level" stuff, loading files, setting up the ugly inner bits of FMod, and all that. Basically it manages the actual audio system itself. 

SoundController, is meant to be the system for actually interacting with sounds, playing them, looping sounds and such. 

While they are similar in that they both work with audio/sound stuff, the are separate for a reason, in general AudioManager should be mostly a blackbox, most developers shouldn't have to interact with it directly. And by extension SoundController should **not** be a child instance of AudioManager, they are two separate things that happen to work together.

**Comment by BraedonWooding** [comment]
Okay that's completely understandable, I'll move it out, but will keep AudioManager as an instance unless that should also remain static due to it being blackbox driven?

**Comment by BraedonWooding** [comment]
Okay, I have updated the description since quite a bit changed (just removal of more unnecessary classes and now AudioManager is a static class with SoundController being instance driven)

**Comment by dustinwloring1988** [comment]
could you get this to work with the latest version of unity

**Comment by BraedonWooding** [comment]
@dustinwloring1988 This will work on Unity 5.6.3f3 (as per my last commit) as that is the version of unity that the project runs on but will not work on the 2017 builds because the project is not currently on the 2017 builds.  That is because they are unstable (due to their beta nature) and because we have to prepare for them.  

The last preparation took around three months to merge but that was due to a bug in the unity version which took around a month for them to fix properly.  I expect a merge to 2017 to take around 2 months due to the massive amount of work required to move :D.

**Comment by dustinwloring1988** [comment]
Ok thanks i tired that originaly and it did not work but i reinstalled unity works great now.   What all needs worked on as im willing to help with anything..

**Comment by BraedonWooding** [comment]
Asking on discord could be beneficial as you will gain a 'wider' view of various systems that need improvements, also looking at the issues for areas that people aren't already working on (since multiple people working on a PR can be sometimes a bit of a nightmare to handle everything and in the past people have just split the PR into two smaller parts).  I would be happy to go over in more depth all the areas that currently don't have people assigned on discord since those are the 'proper' channels.

But to shortly go over them there are the big things (probably a month of work);
- Job System
- Effects (like fire...)
- Integrate Fluids and Utilities
Smaller Things;
- UI Improvements
- Minimap
- Saving/Loading Jobs
There is a long list [here](#32).  Once again however, this 'thread' is for things that relate to this specific PR which is the separation of the world and game into two separate controllers and as to keep this relevant if you have any further questions or inquiries either open an issue or come over and chat on the discord [here](https://discord.gg/68hkpSA).  :D

**Comment by BraedonWooding** [comment]
Reopening to make travis recheck

**Comment by BraedonWooding** [comment]
Closing since I don't have time to finish it.  I will merge in the mouse stuff when I have time to finish it

**Comment by BraedonWooding** [comment]
I'm going to work a bit on this but I don't expect to be done for quite a while.

**Comment by BraedonWooding** [comment]
Due to the major changes occuring outside this it has become a bit unwieldly to fix so I’m going to just start from scratch but use this as a reference :)

**Comment by koosemose** [comment]
You might want to break it up into many smaller PRs this time around. Makes for cleaner merging and easier to overview

**Pull request closed without merging**
