### PR TITLE
Replaced a lot of ContainsKey calls with TryGetValue calls

### PR DESCRIPTION
**Pull request by NogginBops**
### What this PR does

Replaces a lot of `ContainsKey` calls with `TryGetValue` as that is basically always what you want to do when you call `ContainsKey`. And if you really just want the `ContainsKey` functionality you just use `TryGetValue` and discard the actual value.

This will 9/10 times make the code cleaner and 10/10 times make the code more performant.

Now we just need C#7 to make all the `TryGetValue` calls so much nicer to look at.

### CODE REVIEW

**Comment by BraedonWooding** [comment]
If we just want the ContainsKey functionality then we should just use ContainsKey.  It is only if we have code that is;

```csharp
if (map.ContainsKey(x)) {
  return map[x];
}
```
That we should use TryGetValue.

**Comment by NogginBops** [comment]
There are a lot of cases where the `ContainsKey` call and the subsequent indexing is kind of obfuscated.

But yeah there are a few `ContainsKey` that I left because they where actually just contains checks, but I'm almost certain that in some way they are also indexing that value somewhere. 

Anyways, all of the things I have changed are all things where the `ContainsKey` call was followed by an indexing call.

**Comment by BraedonWooding** [comment]
Looks good (once checks pass), while CircularBuffer probably should be a separate commit but its fine to me.

**Comment by NogginBops** [comment]
Just fixed all the style-copping, yeah the circ-buffer should probably (technically) be another commit.
But if someone could do a second pass and check it's maybe better than the thing that was there before; then I think we can commit it here.

Maybe it's not quite strait forward how the circ-buffer works. So it might do with some comments explaining the idea.

**Comment by BraedonWooding** [comment]
I mean people can always google it since we also don't want to go overboard and have the entire wikipedia page in comments.  I think it is relatively clear what it does from the comments there already (to be fair I already knew what it was so it is a bit too anecdotal).

I agree someone else should give it a lookover I may have missed something :).

**Pull request merged**
