### PR TITLE
Changing jobs to be a Suspend/ Unsuspend based model

### PR DESCRIPTION
**Pull request by kd7uiy**
This is the start of a massive improvement in the job system. I would like a bit of feedback as to how this is going so far, but it seems to do everything that was previously done, although the order can be a bit strange (Which is okay, the order will be fixed in another PR).

This is a part of the solution proposed in #198, (4). It should be good enough to help with things further down the line, but more optimization might be possible.

### CODE REVIEW

**Comment by NogginBops** [comment]
I just brushed over the changes, but in general it looks good.
It is a good direction to go for the job system. 👍

**Comment by koosemose** [comment]
While I realize it is probably because that is the file where the previous reevaluate function was called, a callback in furniture is not needed, and may well trigger a reevaluation when it's not needed. RoomManager has the Removed event, which will only be called when a room is actually removed (changing the potential reachability of a job), I would suggest using that rather than creating a new event.

Additionally, you shouldn't use the cb prefix (this *should* be caught by stylecop, but it looks like you've added an exception for it, which is bypassing the style guide)

**Comment by kd7uiy** [comment]
In my opinion, this is ready to add to the build. I have verified that jobs are added, taken one at a time, and seem to be worked in a logical fashion. More checks are always good with something this large of a change, however.

**Comment by koosemose** [comment]
I'm confused by your last commit, as that was something that was previously done. Was that part just temporarily not working in your PR, or did it somehow temporarily break?

**Comment by kd7uiy** [comment]
Did a bit more playing, two more items of note. Haven't figured out why yet, and these might have been existing to some extent, not sure.

1. The hauling doesn't seem to be working.
2. If there is an item on the tile where one places goods (Or maybe where they are produced too?), it will cause some interesting conflicts. It should be moved away first. While we are at it, we should do something similar if an item is in a spot where we are building something.

**Comment by koosemose** [comment]
Clarify on hauling not working please. In general it worked previously, though the original version of the job suspend on inventory unavailable did cause it to delay for a bit.

If I remember correctly originally a crew should be disallowed to drop a different type of inventory on a tile than it already contains, I can't remember offhand if this was done simply by preventing it or using the "drop to nearest clear tile" function (which I can't remember the exact name of). I think this should be the preferred behavior for dropping in an occupied tile, rather than moving first. But yes in the case of inventory it should be moved first when building. This was one of the changes that was always waiting for the "new job system".

**Comment by kd7uiy** [comment]
The hauling now works. As it stands right now, older jobs are always more important then newer ones, and as old jobs are suspended and not stopped, there are some interesting behaviors such as:

1. When mass deconstructing, break down the walls one at a time, then carry to stockpile.
2. Old stockpiles are always higher priorities then, say, furnaces.

I don't think these are problems that should keep this update from being accepted, as they will be fixed when we add in the queue prioritization, but it is worth noting.

**Pull request merged**
