### PR TITLE
Room pathing helper

### PR DESCRIPTION
**Pull request by koosemose**
Adds FindPathToRoom and IsRoomReachable, to aid in finding out if a room (and anything contained in that room) is reachable, and possibly a rough idea of how to get there, without requiring a full tile path.

Includes needed RoomGoalEvaluator.

### CODE REVIEW

**Comment by NogginBops** [comment]
`IsRoomReachable` is a bad idea, it will waste a lot of time doing path-finding just to be discarded.
One should always try and do the proper path-finding and then use the result if valid or do something else if it's not.

**Comment by koosemose** [comment]
IsRoomReachable is meant for uses that explicitly don't care what the path is, only that it can be pathed to, so avoids creating a List object on top of everything else that will only get discarded. If you have an idea of how to determine if a room is reachable without using pathfinding, I'm open to suggestions.

**Comment by kd7uiy** [comment]
Try and do isn't always the best approach. If you can do a relatively simple check that doesn't require a lot of resources then it can be good to check something before doing something that takes a lot of resources.

Overall I don't think there will be a huge number of rooms. Even 100 would be unlikely, fewer is far more likely. An exhaustive pathfinding for rooms thus shouldn't take a long time. Doing it instead of doing the far more expensive tile pathfinding can help considerably.

**Comment by NogginBops** [comment]
But here the ``IsRoomReachable` is not doing a faster thing than the `FindPathToRoom`. They are doing the same thing, then the Try and do method is always superior, always. If there was a fast-path that could say that a path didn't exist I would not be against that, but as this is not that, I'm against it.

**Comment by kd7uiy** [comment]
I've been thinking about it, and I have an even faster way. The fastest way is to basically do a flood fill over the graph, if you find the room you are done, if you have checked all rooms you don't have a connection. That will be coming soon.

**Comment by koosemose** [comment]
Yes but this is for when there is no Do wanted, Try and Do isn't better when no Do is wanted. Admittedly it's not a *huge* improvement, but it's better to get the path, and not turn it into a list, than it is to get the path and turn it into a list when that list is never needed. 

It's not about faster, it's about not generating unneeded garbage. 

If this were used to find out if there was a room path, then another call was made to the other function to actually get a path, then yes that would be worse. This is simply to answer the question "Are these rooms connected" for which it is avoiding creating an unneeded object.

**Comment by koosemose** [comment]
@kd7uiy if you can do floodfill through the graph, then, assuming that's faster than actually pathing, that'd be great.

**Comment by NogginBops** [comment]
Will there ever be a time where you don't want a Do? And if that is the case, that can be implemented then. No need to add code that is not used, that is just adding debt to the codebase.

**Comment by kd7uiy** [comment]
The whole reason why this code is being added in is to avoid the do. The current codebase takes forever to figure out that a tile can't be reached. There are a  few changes, including this one, that are designed to make that easier. Take a look at the recent conversation in #algorithms on discord.

**Comment by NogginBops** [comment]
Ok, so this is the fast-path when doing tile-based path-finding. Then I think it's fine, should maybe be documented that this is used for that purpose.

**Comment by koosemose** [comment]
Yeah, this is basically to avoid having to do a tile pathfind when things are disconnected.

And next time I'm in the code I'll look to adding a.... ugh can't remember the name or syntax, but the usage comment thing where it shows the text on the tooltip.

Really we should be doing that for every function or at least public function, at the very minimum where usage or caveats aren't crystal clear.

**Pull request merged**
