### PR TITLE
[Upgrade] Unity 5.6 Upgrade

### PR DESCRIPTION
**Pull request by BraedonWooding**
**NOTE** Unity 5.6 broke dropdown menus, this is not to be merged till they bring out a new update (which originally was planned for 5.7 but they have back peddled it to either the next hotfix patch or the one after that for 5.6).

5.6 has a few breaking changes (some of these are 5.5 breaking changes):
- Profiler is now under UnityEngine.Profiling,
- Some shader stuff has changed (`mul(UNITY_MATRIX_MVP,*)` with `UnityObjectToClipPos(*)`),
- `[ExpectedException(...)]` is gone, so I had to change them to `Assert.Throws(type, command)` which is why there is a bunch of lambdas this is apparently the 'proper' way to do it despite it looking a little more ugly than the older one (this also required me changing a few unit tests in one of our imported scripts called `DuplicateKeyComparer` but since we don't use that and it's just a unit test I just applied the change).
- `AdSettings.asset` is gone and now is part of `UnityConnectSettings.asset` so this will have to change an asset.
- `ProjectSettings.asset` has a ton of changes, though the current version is not the one to be merged, I'll go through and make sure they mostly match except for new options that are required.

I also will update settings menu options sometime before this gets merged to reflect new options a lot of the code is already in place just requires enabling it basically.

### CODE REVIEW

**Comment by koosemose** [comment]
Is it a good idea to jump multiple versions at once? 5.5 has only recently gotten the worst of the bugs ironed out. Though there are features I am looking forward to on 5.6 (axial sorting *may* greatly simplify some of our sprite code), new minor versions seem to usually take a bit of time before they stabilize to a point that I'm comfortable making the switch.

**Comment by BraedonWooding** [comment]
The point of jumping two is the fact that we want 5.6 features, and not really any 5.5 features.  As I said this is a long term thing I don't expect them to release it for another week (they said 2-3 days but it's unity), so I think it would be better to stay on 5.4 then jump to 5.6 then to increment to 5.5 for a month then spend another while upgrading again to 5.6.  Though I'm happy to upgrade to 5.5 but that's mostly just a line or two and doesn't really give us much/any benefit?

**Comment by koosemose** [comment]
My main thought was simply making it incremental, and just minimizing things that can break. Though, unless something was added since the changes were made, the code *should* compile just fine under 5.5 (I know at one point we had conditionals to handle the Profiler/UnityEngine.Profiling change... so in theory, all that should be required to change to 5.5 would be to commit the changes made from loading in 5.5 and *maybe* a change or two if there was an addition that was made since the 5.5 adaptation that used something that changed between versions.

**Comment by BraedonWooding** [comment]
Yeh it will compile just fine under 5.5, I'm pretty sure.  Mhmmm I'm still unsure whether or not we should just do step by step, since in reality a lot of these changes are version 5.6 specific so in 2 weeks or however long we will just be back at this point again?  Is it worth just waiting, or should we introduce 5.5?  As I was saying is there any feature or should we do it purely based on 'principles' or just to get the latest stable?

**Comment by koosemose** [comment]
Really what it comes down to, since it compiles fine in 5.5, and so far (for me) I haven't had any of the issues  I did when the first attempt to go 5.5 happened, it's really just a matter of us running the project under 5.5 for a bit and ensuring no issues crop up. Perhaps make the minor changes needed to make tests run under 5.5. As you said, it will likely be a bit before 5.6 has its bugs ironed out. 

And it's mostly a matter of shrinking our error window. If problems come up from the switch to 5.6, it'd make it simpler to find a solution (or find that there is presently no solution) if we know the problem actually results from 5.6, rather than something from 5.5.

Ultimately, I'll leave it in your hands, because I'll probably be mired in getting the JSON converter (and the resulting JSON) to a satisfactory point for the next week or so (admittedly I could probably convert it by hand in that same time frame, but I'll be more confident in the consistency of the JSON doing it the automated way, plus, working with conversion from object to data to object in a sandbox setting should make it simpler for me to integrate the json into the prototype manager.) I'm more offering my thoughts on things, rather than making a statement on how I think it should be done.

**Comment by BraedonWooding** [comment]
Mhmmm, while my programmer's laziness is trying to kick in, I do feel it could yes be beneficial to atleast have a window of 5.5 to make sure issues are either 5.5 or 5.6.  I'll push a variant sometime in the next 12 hrs (aka 'tomorrow'), however I'll keep this open since it still needs some long term testing so if anyone passerby wants to test its easy and here.

**Comment by NogginBops** [comment]
I think as we really don't have a finished our even payable game yet, there is not really any concern with stability. If there are a few more bugs it doesn't really matter as they have to be solved in time anyway. As long as it's not game breaking, I say go for it, better do it now than later.

**Comment by koosemose** [comment]
It's not so much stability specifically, but avoiding/isolating/identifying engine related bugs which we may be able to do very little about, particularly as they can be frustrating to new developers (and old developers as well), and we're hoping to start attracting new developers soon. 

Of course, a counterpoint may be that being on the most recent version of Unity may be more friendly to new developers.

Ultimately it's about finding the most recent version that doesn't break things, and as is 5.6 has to wait for a patch before it's usable for us.

**Comment by BraedonWooding** [comment]
Yep I agree, I have a PR for 5.5 and I'll keep this open for bug reporting.

**Comment by koosemose** [comment]
Don't forget, when the patch drops to update the Travis unity install link, using the download location from https://unity3d.com/get-unity/download/archive (to remind you, it's downloading the editor for mac for the appropriate version, and using that download link, minus the parameters after the .pkg)

**Comment by BraedonWooding** [comment]
Apparently, the new update has been released, I will test and update this!  Though I may close this and just copy over wanted changes so I can make sure that this doesn't 'revert' any PRs by accident.

**Comment by BraedonWooding** [comment]
Closing to reopen as new PR, since it just makes life easier due to conflicts :D

**Pull request closed without merging**
