### PR TITLE
Cache pathfinding cost

### PR DESCRIPTION
**Pull request by kd7uiy**
Caches the pathfinding cost, from profiling it should gain about 20% performance boost to pathfinding long distances.

### CODE REVIEW

**Comment by BraedonWooding** [comment]
Technically this requires that the pathfinding cost for an object is constant; that is actions like “locking doors”, tiles that are passable unless under condition X and so on aren’t possible.

Not saying we want this functionality more just highlighting that this lockouts that functionality.

**Comment by kd7uiy** [comment]
Note that it updates the cost if the furniture or tiletype are changed, which I believe should be good enough to not be a problem there, but an extra set of eyes could be helpful there.

**Comment by koosemose** [comment]
We already have locking doors to a degree... airlock doors will lock permanently if pressure is wrong and can't be changed.

**Comment by kd7uiy** [comment]
Will make it public for now. We should probably have a state changed modifier of some kind for the furniture, such that if such a thing happens, the pathfinding cost will be updated.

**Comment by koosemose** [comment]
Yeah, that's why that was an "at the very minimum", while it would probably be preferable to have an observer or something, this *will* at least work.

**Pull request merged**
