### PR TITLE
Fixes to default save area

### LINKED ISSUE #240: [Mega Bugs] Temperature/Gas Bugs
There are a lot of bugs to do with temperature and gases and other systems related to just temperature movement, I want to document them here before I go around changing things since they are all connected it is hard to fix them in isolation and see a change.

- The default save file (for map generation) hard codes (and actually increases in the case of walls) the thermal diffusivity of walls, air pumps and the heat generation for RTGs (this only affects the initial walls any new ones use the real values).
- The default save file (for map generation) uses air pumps when it meant to use vents (air pumps are just one way)
- The code to calculate thermal diffusivity between two rooms is way too complicated, it is a complicated concept and hard not to double up but still is way too complicated
- Thermal diffusivity between rooms isn't calculated well if the rooms are east/west only if they are north/south
- Thermal diffusivity between walls is sometimes much higher than it should be
- The map can be rebuilt way too often per frame (impacting performance slightly)

I'm going to start by fixing some of the smaller things on the list (each item will get a single PR though I'll group the save file ones) but since they are all related it makes sense to put them in a single issue.

### PR DESCRIPTION
**Pull request by BraedonWooding**
Partially Completes #240.

Changes air pumps to vents (I presume that was the intention that the air goes both ways rather than just one way).

Removes all the hard coding of parameters (except for open/closeness since that makes sense, don't want to flush everyone out upon load).

Also fixes room behavior.lua for airlocks.

### CODE REVIEW

**Comment by BraedonWooding** [comment]
@koosemose I'll just get you to do a look over since you did the work on `.sav`

**Comment by BraedonWooding** [comment]
Merging once pasts tests, just a small few fixes before we move Parameters away from being saved in some cases.

**Comment by koosemose** [comment]
Need to readd the gas throughput to the air pump (at least for the time being, until we actually separate parameters)... *maybe* the rotation as well, but I suspect that gets figured out by the placement code anyways, so perhaps not needed.

**Comment by BraedonWooding** [comment]
I would have expected the loader to load both the parameters from the prototype and the save file and prioritize save file for conflicts?

**Comment by koosemose** [comment]
I'm pretty sure the json deserialization just creates a new object. 

Though rather than closing, perhaps at least have the addition of the airlock roombehavior addition to the default starting area, and especially the fix to the lua.

**Comment by BraedonWooding** [comment]
Yes I was going to do them in a separate one but I guess it is still related to this.

**Comment by BraedonWooding** [comment]
I'll get you to have a look over it once more (once travis passes) just to confirm that you are happy with it :).

**Comment by koosemose** [comment]
I agree on the separate Parameters (or roughly parameters like structure anyways), But of course that is outside the scope of this PR.

And assuming this passes, everything looks good (admittedly I skimmed the bulk of the .sav, since it's mostly the same thing repeated over and over, and I'm assuming you used fine/replace, so they should all be the same)

**Comment by BraedonWooding** [comment]
They are the same changes (used find/replace).

I'll merge them then.

**Pull request merged**
