### PR TITLE
Update fmod meta data to match the rest of the plugins

### PR DESCRIPTION
**Pull request by BraedonWooding**
This is mainly needed to not only be consistent but also allow us to test in play mode.

It used to only work in the editor and standalone but now it can load during playmode

### CODE REVIEW

**Comment by koosemose** [comment]
I'm a little confused as to what exactly this is doing. Did fmod not work in playmod on macs or something?

**Comment by koosemose** [comment]
That makes sense.... very weird that it only affects it during unit testing. Just make sure that this is tested on windows, just to ensure it doesn't do any weirdness like trying to load the mac version of the plugin on windows... I'm probably just being paranoid... but I always feel like fmod is volatile if poked at, lol

**Comment by BraedonWooding** [comment]
It won't load on windows because the platform OS settings (yeh there are two sections for platforms; unity ui layout strikes again) has it be only Mac OSX 64 bit.

I'll still do a check :)

**Comment by BraedonWooding** [comment]
Works on windows and passes checks so merging

**Pull request merged**
