### PR TITLE
Fixing overlays

### PR DESCRIPTION
**Pull request by buggy213**
### The issue this fixes

Overlays not working properly

### What this PR does

Updates old lua scripts to work with the new room atmosphere system

### CODE REVIEW

**Comment by koosemose** [comment]
I see that *something* changed in the _World scene, it's not absolutely clear *what* changed. Was this intentional?

**Comment by buggy213** [comment]
Yes. Because of the depth shading changes made to PP a while back, the
Overlay mesh wasn't displaying properly. By simply moving the object
backwards, it is able to properly render the overlay.

**Comment by koosemose** [comment]
Very strange, though it wasn't the depth shading changes that caused the issue... I'm not sure what was exactly, but depth shading has been in for a very long time, and I am 100% certain that the overlay worked with depth shading just fine at its previous position. 

I'll see about tracking down the actual cause later with a bisect, just so we can ensure it doesn't cause any other unexpected issues. 

Since this also fixes unupdated Lua, I'll go ahead and merge this, but if I can track down and fix the root bug, I may revert the overlay to it's previous position (though ultimately its position doesn't matter as long as it shows)

**Comment by BraedonWooding** [comment]
Btw I just want to say thanks a ton @buggy213 since this was an issue that plagued me while doing temperature but just not enough for me to sidetrack to find out why it was broken but enough to be annoying, thanks for fixing it :D massive improvement in quality of environment.

**Pull request merged**
