### PR TITLE
Logging change

### PR DESCRIPTION
**Pull request by RyTechro**
### The issue this fixes

A lot of log messages every second in the unity log

### What this PR does

Remove the timeshift log
Add an if statement for State machine logs. This should be added to the setting menu

### CODE REVIEW

**Comment by BraedonWooding** [comment]
> Copied from the previous PR :)

I'm not 100% sure about this set of changes however we already have ways to disable parts of logging, for example there is a 'unity debugger' option under Window/Debugger Channel Control, which allows you to disable debugging for each of the 'categories'.

However, I think removing the game speed log is probably fine as it is clear enough by itself.

Though in saying this there is a currently unused option under the settings menu called 'Logging Level' that allows you to set a certain logging level, which while currently is a toggle (just due to the fact it isn't implemented) there is that avenue to implement it.

If your interested then looking at StreamingAssets/Data/Prototypes/SettingTemplate.json (we use JSON now) and StreamingAssets/CSharp/SettingsMenuFunctions.cs would be a good starting point.  Most likely you would want to update SettingTemplate logging level (line ~250 ish) to take a custom class that you implement in the SettingsMenuFunctions file something as simple as;
```C#
public class LoggingLevelOption : GenericMultiSelect
{
    public override GameObject InitializeElement()
    {
        // Just a basic idea
        GameObject go = MultiSelectHelperFromText(string[] { "Verbatim", "Light", "None" });
        return go;
    }
}
```
> You could also implement an override for the base GenericMultiSelect to allow you to pass in an enum and to convert that enum to string within the class then convert back based upon the index of the combo box 😄 .

You shouldn't have to override anything else in this case (though you may want to for whatever reason).

You would then update Scripts/Models/Settings/SettingsKeyHolder to whatever your using either string or enum (enum using the way I said above), and then could access it at any point like;
```C#
if (SettingsKeyHolder.LoggingLevel == LoggingLevel.Verbatim) {
    // Do x
}
```

**Comment by koosemose** [comment]
The change to the logging in States is unneeded as this sort of thing (booleans separately handled per class to control logging) is one of the things DebugLogger was made to avoid. Messages in any specific group can already be turned off in the way Braedon describes.

Though it might not be a bad idea to have an additional scale of logging levels, and I'm pretty sure the core of DebugLogger already has this functionality it's just not properly hooked up in a way that we can access directly, as for the most part, we've been more interested in changing what's logged based on category rather than the degree those things are logged, and there is also some degree of this as, at the root it still works through Unity's Debug.Log, LogWarning, and LogError, but it might still be useful, for example, to show all errors, regardless of category but not other things of the categories (since if a category is turned on, it it uses the appropriate Debug.Log variant, so it is still printed even if you're not showing it in Unity).

It should be trivial to make it so that you set a log level from 1-3 (or perhaps 0-2, or enum based), and one does all, next does warnings and errors only and last does errors only, rather than layering an additional concept of log severity on top of what unity already does. Could possibly make it so there's two types of logging level... don't know proper terminology for them but something like filter, which would only show those log levels in categories that are turned on (so if you're only showing Pathfinding, at Log Level 3, you *only* see Pathfinding Errors), and override which would show all logs of that level regardless of category (so if you have Pathfinding and Override Log Level 3, you'd see all Pathfinding logs, and all Errors regardless of category). I'm not sure which would be more useful and/or if both should be an option. 

Either way, changes to the logger should primarily be in my repo (which I should really move to OrderOfThePorcupine, so it is accessible if I disappear), as it needs to be compiled to a DLL (if used directly as code it causes Unity to link it to where the log is emitted in the logger itself, which is a big annoyance, and compiling to a DLL prevents this).

**Comment by koosemose** [comment]
Also note that it is usually a good idea to make an issue before a PR to be sure you don't waste time working on something that would never be accepted or that someone else is working on.

Discussing it on the discord ( https://discord.gg/68hkpSA ) is often acceptable as well, especially for something smaller like this. Discord can give you a faster response time (since Braedon and I are in nearly opposite time zones, usually at least one of us will notice a discord message), of course if it's something we feel needs a bigger discussion, we may direct you to make an issue.

**Comment by BraedonWooding** [comment]
I'm not merging this for the reason's koosemose mentioned above, so closing :).

**Pull request closed without merging**
