### PR TITLE
[Conflicted] Make all lower-bar menus closable by pressing the button that opened them

### PR DESCRIPTION
**Pull request by NogginBops**
### What this PR does

Makes it so that all menus in the lower bar can be closed again by pressing the button that opened it again.

### TODO

- [ ] Fix so that the Options menu can't be toggled when the settings menu is open (But for now this seems like a resonable temporary trade-off for getting a more convenient menu system).

### CODE REVIEW

**Comment by kd7uiy** [comment]
Looks good, but it doesn't close open dialogs, unless they are both MenuLeft ones. Not sure how easy it would be to add, but worth considering.

**Comment by NogginBops** [comment]
It's not as strait forward as it should be, because the system that controls the left menu has no connection to the code that handles the dialog menus.

**Comment by BraedonWooding** [comment]
This will change with my PR, the dialog system is going to now represent a stack so you should be able to call `WorldController.Instance.DialogBoxManager.CloseDialogs()` (or something similar to this).

Otherwise it is quite hairy since you would have to check each dialog to see if it is open.

**Comment by NogginBops** [comment]
What do you mean with checking each dialog to see if it's open?

**Comment by BraedonWooding** [comment]
Well DialogBoxManager doesn't track if a dialogbox is open and especially doesn't track if there is a stack of them open.  But you can access each possibly opened dialog box through it.  So the code would look something like;

```csharp
DialogBoxLoadSaveGame flsb = DialogBoxManager. DialogBoxLoadSaveGame;
if (flsb.ActiveInHierachy) flsb.CloseDialog();
// .. and so on for each possible box
```

**Comment by koosemose** [comment]
This should be good for merge once conflicts are resolved.

Though as a side note, using the TODO with checkboxes makes it appear (to me at least) that there is more that is intended to be done for this PR.

**Pull request merged**
