### PR TITLE
Switch to Json Data (for prototypes)

### PR DESCRIPTION
**Pull request by koosemose**
It's been a long time coming, but I believe this should be functional and have all capabilities as it did under XML data. 

### Improvements over XML
Can have multiple prototype types per file
Can have same prototype type in multiple files
Automatically reads all Json files under StreamingAssets\Data\Prototypes
Multiple "handlers" (json readers) can be attached to each prototype type (as an example, Furniture could both be read in by furniture, and a special handler for inventory to automatically create crated furniture), this is not yet taken advantage of, but may be in the future.
Json is sexier ;)

Note: I've left in the xml prototype files for now, along with the functions to read the xml, just in case some element is missing, as it is much easier to reintegrate from something within the same code base rather than having to track back in git history.

### CODE REVIEW

**Comment by BraedonWooding** [comment]
Sweet, I'll add anything that you've missed in relation to any of my stuff :)

**Comment by NogginBops** [comment]
The travis check has failed, this should probably be fixed before merging. Looks like there is some stylecop related errors.

**Comment by koosemose** [comment]
How peculiar... I ran stylecop and cleaned up all the issues reported, and my one post stylecopping change didn't touch any of the files with the issues reported in stylecop...

And it still reports as clean... Digging into it further, it appears to be complaining about the header in most of these files (Line 7, which is the last line of the header), which apparently my version of monodevelop has no issue with, but the version ran on Travis does. Well that's mildly annoying, I'll have to go in and do them all manually.

**Comment by koosemose** [comment]
And that *should* take care of them all, of course, since I can't rely on monodevelop to spot them, I've got to rely on them being spotted by travis. Also, nice to see you around. :)

**Comment by NogginBops** [comment]
Tests pass now 👍. It's nice to see work being done on the project too :) Keep up the good work

**Comment by koosemose** [comment]
I've been working on this particular project for a VERY long time, most of it spent with the tedious process of changing the files over, and ensuring all the same data is in Json, and then dealing with various classes that were structured in a particular way to suit XML data structures that was either incompatible with Json structures, or at the very least would require bad json design... and of course recovering from WAY too much tedious work. 

I intend to try to keep up at least some amount of work on the project, even if it's only minor things, just to try to keep some life here. Either experimenting with interesting ideas or random optimizations (particularly more hunting down of the many many places we severely abuse the garbage collection).

**Comment by koosemose** [comment]
It's only been 1.6 years in coming... we're nothing if not timely.

**Pull request merged**
