### PR TITLE
Fixed neq comparisons (!= to ~=) in `Furniture.lua`

### PR DESCRIPTION
**Pull request by BraedonWooding**
As the title says fixes it by changing the comparisons

### CODE REVIEW

**Comment by NogginBops** [comment]
Did this code ever work? Or is it Moonsharp that just allowed us to do this?

**Comment by BraedonWooding** [comment]
That is the weird thing, I can't find any source that it allows it and in the list of differences [here](http://www.moonsharp.org/moonluadifferences.html) it doesn't list it as an allowed operation (it definitely isn't in LUA)

**Comment by BraedonWooding** [comment]
Okay despite there being no documentation on it I have found the answer in the source code (nothing like searching through some source code for undocumented features).

The answer is that it changes `!=` to `~=` when parsing (it literally changes the token as you can see on this [line](https://github.com/xanathar/moonsharp/blob/84eff75f0569edbe063de995973b940416e51478/src/MoonSharp.Interpreter/Tree/Lexer/Lexer.cs#L168)).

This doesn't mean honestly that this shouldn't be merged, I would still count using != as a bug since;
- other lua interpreters don't support it so changing implementations requiring changing it anyway
- no documentation that moonsharp supports it so I would classify it as undefined behaviour
- every lua linter will count it as an error and using lua linters will help ensure that our lua code is correct since we can't check it any other way.

**Comment by NogginBops** [comment]
Yeah, this seems like a good change to me.

**Pull request merged**
