### PR TITLE
[Update] Unity 5.5 Compatibility Patch

### PR DESCRIPTION
**Pull request by BraedonWooding**
Moves the project to Unity 5.5.  And updates readme version.

### CODE REVIEW

**Comment by BraedonWooding** [comment]
@koosemose I'll get your signoff on this since it's a 'major' change (in reality its minor we had all the compatability already done more of a principle).

**Comment by koosemose** [comment]
I'm surprised this isn't erroring out on the unit tests, as you forgot to change the Unity download script for the tests to use 5.5, so it's still building in 5.4 which I *thought* would error on `Using UnityEngine.Profiling`

**Comment by BraedonWooding** [comment]
That is odd.  I'll fix that

**Comment by BraedonWooding** [comment]
I don't know if I did it right, but I put in the last version of 5.5 which was used to compile the project.  So this check may fail, but I'm pretty sure I did it right.

**Comment by koosemose** [comment]
The link was wrong, it has a hashcode in the link which changes between versions, best way to get new link is download mac editor (not installer) from https://unity3d.com/get-unity/download/archive for the version you want, and check what address it is downloading from, it *may* have info after the .pkg, but you shouldn't need that (let's see if this succeeds before we take anything I say here as correct)

**Comment by koosemose** [comment]
Everything seems to be working now... though it still confuses me a bit that it didn't fail while being compiled with 5.4, since you removed the version check.

**Pull request merged**
